\version "2.19.21"

% Generated by concertc, version 1.0.0

{
 \time 4/4
 \clef treble
 b''''4 cis''''8 cis''''8 fis''''2 b''''4 cis''''4 fis''''2 a''''4 fis''''8 e''''8 cis''''8 b''''8 fis'''4 fis'''16 g'''16 a'''16 b''''16 cis''''16 d''''16 e''''16 fis''''16 g''''16 a''''16 
}
